apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose-v2.0-sandy.yml -o piggymetrics -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: account-service
  name: account-service
spec:
  ports:
  - name: "6000"
    port: 6000
    targetPort: 6000
  selector:
    io.kompose.service: account-service
status:
  loadBalancer: {}
