apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose-v2.0-sandy.yml -o piggymetrics -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: account-service
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: account-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f docker-compose-v2.0-sandy.yml -o piggymetrics -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: account-service
    spec:
      containers:
      - env:
        - name: ACCOUNT_SERVICE_PASSWORD
          value: password
        - name: CONFIG_SERVICE_PASSWORD
          value: password
        - name: MONGODB_PASSWORD
          value: password
        image: sandyhu/piggymetrics-account-service
        imagePullPolicy: ""
        name: account-service
        ports:
        - containerPort: 6000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
