apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose-v2.0-sandy.yml -o piggymetrics -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: config
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f docker-compose-v2.0-sandy.yml -o piggymetrics -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: config
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          value: password
        image: sandyhu/piggymetrics-config:v1.0.4
        imagePullPolicy: "Always"
        name: config
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
