apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose-v2.0-sandy.yml -o piggymetrics -c
    kompose.service.type: loadbalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: monitoring
  name: monitoring
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 8080
  - name: "8989"
    port: 8989
    targetPort: 8989
  selector:
    io.kompose.service: monitoring
  type: LoadBalancer
status:
  loadBalancer: {}
