hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

zuul:
  routes:
    auth-service:
      path: /uaa/**
      url: http://auth-service:5000
      stripPrefix: false
      sensitiveHeaders:

    account-service:
        path: /accounts/**
        serviceId: account-service
        stripPrefix: false

    statistics-service:
        path: /statistics/**
        serviceId: statistics-service
        stripPrefix: false

    notification-service:
        path: /notifications/**
        serviceId: notification-service
        stripPrefix: false

ribbon:
  eureka:
    enabled: false

account-service:
  ribbon:
    listOfServers: http://account-service:6000/accounts/

statistics-service:
  ribbon:
    listOfServers: http://statistics-service:8888/statistics/

notification-service:
  ribbon:
    listOfServers: http://notification-service:8000/notifications/

server:
  port: 4000
